/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopracticon4;

import java.util.HashSet;

/**
 *
 * @author Usuario
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    public static HashSet<Alumno> listaAlumnos = new HashSet<>();
    public static HashSet<Materia> listaMaterias = new HashSet<>();
    /**
     * Creates new form MenuPrincipalFrame
     */
    public MenuPrincipalFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AgregarAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AgregarMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Inscripción = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        SalirSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        AgregarAlumno.setText("Agregar Alumno");
        AgregarAlumno.addActionListener(this::AgregarAlumnoActionPerformed);
        jMenu1.add(AgregarAlumno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        AgregarMateria.setText("Agregar Materia");
        AgregarMateria.addActionListener(this::AgregarMateriaActionPerformed);
        jMenu2.add(AgregarMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Registro");

        Inscripción.setText("Inscripción");
        Inscripción.addActionListener(this::InscripciónActionPerformed);
        jMenu3.add(Inscripción);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");

        SalirSistema.setText("Salir del Sistema");
        SalirSistema.addActionListener(this::SalirSistemaActionPerformed);
        jMenu4.add(SalirSistema);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMateriaActionPerformed
    escritorio.removeAll();
    escritorio.repaint();
    
    VistaMaterias vm = new VistaMaterias(listaMaterias);
    vm.setVisible(true);
    escritorio.add(vm);
    
    // Centrar subventana
    int x = (escritorio.getWidth() - vm.getWidth()) / 2;
    int y = (escritorio.getHeight() - vm.getHeight()) / 2;
    vm.setLocation(x, y);
    
    escritorio.moveToFront(vm);
    }//GEN-LAST:event_AgregarMateriaActionPerformed

    private void AgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAlumnoActionPerformed
    escritorio.removeAll();
    escritorio.repaint();
    
    VistaAlumno va = new VistaAlumno(listaAlumnos);
    va.setVisible(true);
    escritorio.add(va);
    
    // --- LÍNEAS PARA CENTRAR ---
    int x = (escritorio.getWidth() - va.getWidth()) / 2;
    int y = (escritorio.getHeight() - va.getHeight()) / 2;
    va.setLocation(x, y);
    // ---------------------------
    
    escritorio.moveToFront(va);
    }//GEN-LAST:event_AgregarAlumnoActionPerformed

    private void InscripciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripciónActionPerformed
        escritorio.removeAll();
    escritorio.repaint();
    
    VistaInscripcion vi = new VistaInscripcion();
    vi.cargarAlumnos();
    vi.cargarMaterias();
    vi.setVisible(true);
    escritorio.add(vi);
    
    int x = (escritorio.getWidth() - vi.getWidth()) / 2;
    int y = (escritorio.getHeight() - vi.getHeight()) / 2;
    vi.setLocation(x, y);
    
    escritorio.moveToFront(vi);
    }//GEN-LAST:event_InscripciónActionPerformed

    private void SalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarAlumno;
    private javax.swing.JMenuItem AgregarMateria;
    private javax.swing.JMenuItem Inscripción;
    private javax.swing.JMenuItem SalirSistema;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
