package trabajopracticon4;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author federico
 */
public class VistaAlumno extends javax.swing.JInternalFrame {
    private HashSet<Alumno> listaAlumnos;
    /**
     * Creates new form VistaAlumno
     */
    public VistaAlumno(HashSet<Alumno> listaAlumnos) {
        initComponents();
        this.listaAlumnos = listaAlumnos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        lbLegajo = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lbTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbTitulo.setText("Formulario de Alumnos");

        lbLegajo.setText("LEGAJO:");
        lbLegajo.setPreferredSize(new java.awt.Dimension(82, 27));
        lbLegajo.setSize(new java.awt.Dimension(82, 27));

        lbApellido.setText("APELLIDO:");
        lbApellido.setPreferredSize(new java.awt.Dimension(82, 27));
        lbApellido.setSize(new java.awt.Dimension(82, 27));

        lbNombre.setText("NOMBRE:");
        lbNombre.setPreferredSize(new java.awt.Dimension(82, 27));
        lbNombre.setSize(new java.awt.Dimension(92, 27));

        txtLegajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLegajoFocusLost(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(lbTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo)
                        .addGap(38, 38, 38)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        if(txtLegajo.getText().isEmpty() || txtApellido.getText().isEmpty() || txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe completar los 3 campos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                int nroLegajo = Integer.parseInt(txtLegajo.getText());
                boolean existeLegajo = alumnoExiste(nroLegajo);

                if(!existeLegajo){
                    String nombre = txtNombre.getText().trim();
                    String apellido = txtApellido.getText().trim();
                    if(nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+") && apellido.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")){
                        Alumno alummno = new Alumno(nroLegajo,apellido,nombre,null);
                        MenuPrincipalFrame.listaAlumnos.add(alummno);
                        txtLegajo.setText("");
                        txtApellido.setText("");
                        txtNombre.setText("");
                        JOptionPane.showMessageDialog(this, "Alumno dado de alta exitosamente!","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Debe ingresar bien los datos. En apellido y nombre solo letras","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                    }
                }

            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "En numero de legajo solo pueden ir numeros","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int legajo = Integer.parseInt(txtLegajo.getText());

        if(alumnoExiste(legajo) && !txtNombre.getText().isEmpty() && !txtApellido.getText().isEmpty()){
            String nombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            if(nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+") && apellido.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")){
                for(Alumno a: listaAlumnos){
                    if(a.getLegajo() == legajo){
                        a.setApellido(txtApellido.getText());
                        a.setNombre(txtNombre.getText());
                        JOptionPane.showMessageDialog(this, "Alumno guardado correctamente!");
                        break;
                    }
                }
                txtLegajo.setText("");
                txtApellido.setText("");
                txtNombre.setText("");

            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtLegajoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLegajoFocusLost
        try {
            int legajo = Integer.parseInt(txtLegajo.getText());
            boolean legajoExiste = alumnoExiste(legajo);
            if(legajoExiste){
                for(Alumno a: listaAlumnos){
                    if(a.getLegajo() == legajo){
                        txtApellido.setText(a.getApellido());
                        txtNombre.setText(a.getNombre());
                        break;
                    }
                }
            } else {
                txtApellido.setText("");
                txtNombre.setText("");
            }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "En numero de legajo solo pueden ir numeros","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtLegajoFocusLost

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "Esta seguro que desea salir ?", "Salir",JOptionPane.YES_NO_OPTION);

        if(respuesta == JOptionPane.YES_NO_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbLegajo;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private boolean alumnoExiste(int nroL){
        boolean existe = false;
        for(Alumno alumno: listaAlumnos){
            if(alumno.getLegajo() == nroL){
                existe = true;
                break;
            }
        }
        
        return existe;
    }
}
